using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace synnex_mvc_app_1.Models;

public class Student
{
	//[Key]
	//Primary Key + AutoGenerated
	//[Key]
	//[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	public int Id { get; set; }

	//public string AdmissionNo { get; set; }
	[Required]
	[StringLength(100)]
	public string Name { get; set; }
	[Required(ErrorMessage ="Age is mandatory")]
	[Range(18,90)]
	public int? Age { get; set; }
	public string Address { get; set; }
}


